name: 'Oplyst International, LLC | Official Website'
favicon: null
layout_spectrum: 0.3193491285201162
typography_spectrum: 0.43036376498639584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.03698053560219705
  lightness: 0.710190397221595
  saturation: 0.30887474748305976
  rhythmicContrast: 0.15044908481650054
purpose: []
