analytics:
  google: UA-73702823-1
color:
  brandColors:
    - '#060808'
    - '#ffffff'
    - '#01ffff'
    - '#a3a8aa'
    - '#fdfc02'
  brandStrength: 1
  lightness: 0.625
  rhythmicContrast: 0.75
  saturation: 0.375
cta: {}
layout_spectrum: 0.217061
name: '| Oplyst International, LLC'
opengraph: {}
purpose: []
typography_spectrum: 0.930743
