name: 'Oplyst International, LLC | Official Website'
favicon: null
layout_spectrum: 0.3193491285201162
typography_spectrum: 0.43036376498639584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060808'
    - '#ffffff'
    - '#01ffff'
    - '#a3a8aa'
    - '#fdfc02'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
