name: 'Oplyst International, LLC'
favicon: null
layout_spectrum: 0.25647
typography_spectrum: 0.63996
title: 'Oplyst International, LLC | Official Website'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73702823-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060808'
    - '#ffffff'
    - '#01ffff'
    - '#a3a8aa'
    - '#fdfc02'
  brandStrength: 0.9375
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
