name: Oply Consulting
favicon: null
layout_spectrum: 0.203
typography_spectrum: 0.930743
title: Oply Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73702823-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060808'
    - '#ffffff'
    - '#01ffff'
    - '#a3a8aa'
    - '#fdfc02'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
