analytics:
  google: UA-73702823-1
color:
  brandColors:
    - '#060808'
    - '#ffffff'
    - '#01ffff'
    - '#a3a8aa'
    - '#fdfc02'
  brandStrength: 0.9375
  lightness: 0.4375
  rhythmicContrast: 0.5
  saturation: 0.75
cta: {}
layout_spectrum: 0.261824
name: 'Oplyst International, LLC'
opengraph: {}
purpose: []
typography_spectrum: 0.930743
